import { KoiInfo } from '../types/garden';

export const KOI_COLLECTION_DATA: KoiInfo[] = [
  {
    id: 0,
    name: 'Kohaku (Jumbo)',
    kanji: '紅白',
    romaji: 'Kohaku',
    variety: 'kohaku',
    category: 'Gosanke',
    size: 'jumbo',
    lengthCm: 72,
    description: 'The undisputed monarch of the garden. A mature female koi with a pristine porcelain-white body adorned with deep step-like scarlet markings (Danmoyo).',
    patternDescription: 'Three-step red (sandan) pattern over solid pearl white.',
    colorPalette: ['#ffffff', '#e83e1b'],
    rarity: 'Prized',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 1,
    name: 'Taisho Sanke',
    kanji: '大正三色',
    romaji: 'Taisho Sanshoku',
    variety: 'sanke',
    category: 'Gosanke',
    size: 'medium',
    lengthCm: 46,
    description: 'A classic tricolor variety originating in the Taisho era, featuring crisp sumi (black) lacquer spots resting gracefully over red and white ground.',
    patternDescription: 'Balanced scarlet islands with small lacquer-black shoulder accents.',
    colorPalette: ['#ffffff', '#e83e1b', '#1a191d'],
    rarity: 'Prized',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 2,
    name: 'Yamabuki Ogon (Jumbo)',
    kanji: '山吹黄金',
    romaji: 'Yamabuki Ogon',
    variety: 'yamabuki',
    category: 'Hikarimuji',
    size: 'jumbo',
    lengthCm: 68,
    description: 'A magnificent metallic golden koi resembling the golden mountain rose (Yamabuki). Catches sunlight deep under the bridge.',
    patternDescription: 'Solid lustrous metallic yellow-gold from head to tail fin.',
    colorPalette: ['#e4a824', '#f7cf54', '#8a6210'],
    rarity: 'Prized',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 3,
    name: 'Showa Sanshoku (Jumbo)',
    kanji: '昭和三色',
    romaji: 'Showa Sanshoku',
    variety: 'showa',
    category: 'Gosanke',
    size: 'jumbo',
    lengthCm: 70,
    description: 'A powerful, heavy-shouldered koi with a midnight black ground upon which fierce crimson and pure white patterns surge like breaking waves.',
    patternDescription: 'V-shaped black head blaze (menware) and black fin joints (motoguro).',
    colorPalette: ['#141416', '#e43a18', '#edeae4'],
    rarity: 'Prized',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 4,
    name: 'Orenji Ogon (Gin Rin)',
    kanji: 'オレンジ黄金 (銀鱗)',
    romaji: 'Orenji Ogon (Gin Rin)',
    variety: 'orenji',
    category: 'Hikarimoyo',
    size: 'medium',
    lengthCm: 44,
    description: 'Radiant vibrant tangerine-orange scales treated with diamond reflection (Gin Rin), glimmering brightly as it glides through sunlit ripples.',
    patternDescription: 'Uniform metallic orange with sparkling reflective diamond scales.',
    colorPalette: ['#ea6a1a', '#fba654', '#ffffff'],
    rarity: 'Rare',
    scaleType: 'Gin Rin (Diamond Scaled)',
  },
  {
    id: 5,
    name: 'Karasugoi',
    kanji: '烏鯉',
    romaji: 'Karasugoi',
    variety: 'karasugoi',
    category: 'Kawarimono',
    size: 'medium',
    lengthCm: 48,
    description: 'The mystical "Crow Carp". Velvet obsidian black back with a warm bronze underbelly. Skulks near the bottom rocks like a shadow.',
    patternDescription: 'Pitch black top body fading into soft golden belly.',
    colorPalette: ['#0f0f11', '#1f1e22', '#c98a3b'],
    rarity: 'Uncommon',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 6,
    name: 'Tancho Kohaku',
    kanji: '丹頂紅白',
    romaji: 'Tancho Kohaku',
    variety: 'tancho',
    category: 'Tancho',
    size: 'medium',
    lengthCm: 47,
    description: 'Named after the sacred Japanese red-crowned crane. A snow-white body bearing a solitary, perfectly rounded crimson sun crest upon its forehead.',
    patternDescription: 'Pristine white body with a single circular red crest centered between the eyes.',
    colorPalette: ['#faf9f5', '#e42c16'],
    rarity: 'Prized',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 7,
    name: 'Shiro Bekko',
    kanji: '白別甲',
    romaji: 'Shiro Bekko',
    variety: 'bekko',
    category: 'Bekko',
    size: 'small',
    lengthCm: 26,
    description: 'An agile juvenile with milky white skin decorated with small, crisp stepping-stone black markings along its dorsal ridge.',
    patternDescription: 'Spaced black tortoiseshell spots on clean white field.',
    colorPalette: ['#f5f4ef', '#181719'],
    rarity: 'Common',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 8,
    name: 'Taisho Sanke (Juvenile)',
    kanji: '若鯉大正三色',
    romaji: 'Waka Sanke',
    variety: 'sanke',
    category: 'Gosanke',
    size: 'small',
    lengthCm: 24,
    description: 'A lively, curious young tricolor who darts quickly whenever food pellets touch the surface.',
    patternDescription: 'Vivid red cheek spots and emerging sumi markings.',
    colorPalette: ['#ffffff', '#ea4320', '#181719'],
    rarity: 'Common',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 9,
    name: 'Asagi',
    kanji: '浅黄',
    romaji: 'Asagi',
    variety: 'asagi',
    category: 'Asagi',
    size: 'medium',
    lengthCm: 45,
    description: 'One of the oldest prehistoric koi bloodlines. Features a mesmerising indigo-blue pinecone netting pattern across its back with rust-orange cheeks and fins.',
    patternDescription: 'Netted blue-grey scales with burnt orange ventral flanks and pectorals.',
    colorPalette: ['#445b72', '#7b95ad', '#db5a26'],
    rarity: 'Rare',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 10,
    name: 'Platinum Ogon (Butterfly)',
    kanji: '白金黄金 (鰭長)',
    romaji: 'Platinum Ogon (Hirenaga)',
    variety: 'platinum',
    category: 'Hirenaga',
    size: 'medium',
    lengthCm: 48,
    description: 'A breathtaking celestial sight. Solid metallic mirror-white with exaggerated flowing fins and tail resembling butterfly silk wings.',
    patternDescription: 'Solid metallic platinum white with elongated trailing fins.',
    colorPalette: ['#f2f4f7', '#ffffff', '#c5d1dc'],
    rarity: 'Prized',
    scaleType: 'Butterfly (Hirenaga)',
  },
  {
    id: 11,
    name: 'Chagoi (The Friendly Leader)',
    kanji: '茶鯉',
    romaji: 'Chagoi',
    variety: 'chagoi',
    category: 'Kawarimono',
    size: 'jumbo',
    lengthCm: 74,
    description: 'The gentle giant and undisputed social anchor of the pond. Brown tea-colored, exceedingly tame, and always the first to approach when human hands reach into the water.',
    patternDescription: 'Solid earthy brown-ochre netting with broad, calm demeanor.',
    colorPalette: ['#8c6b44', '#b08b5c', '#624628'],
    rarity: 'Prized',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 12,
    name: 'Shiro Utsuri',
    kanji: '白写り',
    romaji: 'Shiro Utsuri',
    variety: 'shiroutsuri',
    category: 'Utsurimono',
    size: 'medium',
    lengthCm: 49,
    description: 'Striking monochrome duality: a jet black canvas wrapped in dramatic checkerboard blocks of purest snow white.',
    patternDescription: 'Interlocking checkerboard white patches on deep ink-black body.',
    colorPalette: ['#111113', '#f4f2eb'],
    rarity: 'Rare',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 13,
    name: 'Hi Utsuri (Juvenile)',
    kanji: '緋写り',
    romaji: 'Hi Utsuri',
    variety: 'hiutsuri',
    category: 'Utsurimono',
    size: 'small',
    lengthCm: 25,
    description: 'A fiery young koi with flame-red and coal-black interlocking bands. Energetic and inquisitive.',
    patternDescription: 'Vibrant crimson patterns alternating with midnight black bands.',
    colorPalette: ['#121214', '#de4418'],
    rarity: 'Uncommon',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 14,
    name: 'Kujaku (Butterfly)',
    kanji: '孔雀 (鰭長)',
    romaji: 'Kujaku (Hirenaga)',
    variety: 'kujaku',
    category: 'Hirenaga',
    size: 'medium',
    lengthCm: 47,
    description: 'The "Peacock Koi". Shimmering metallic platinum with Matsuba net scales, blazing orange markings, and long flowing butterfly fins.',
    patternDescription: 'Metallic white with charcoal netting, fiery orange patches, and long pectoral fins.',
    colorPalette: ['#ffffff', '#ea5e1f', '#323438'],
    rarity: 'Prized',
    scaleType: 'Butterfly (Hirenaga)',
  },
  {
    id: 15,
    name: 'Doitsu Kohaku',
    kanji: 'ドイツ紅白',
    romaji: 'Doitsu Kohaku',
    variety: 'doitsu',
    category: 'Doitsugoi',
    size: 'medium',
    lengthCm: 46,
    description: 'A German scaleless crossbreed with smooth porcelain leather skin and sharp, clean lacquer-red islands.',
    patternDescription: 'Mirror-smooth scaleless white body with sharp vermilion islands.',
    colorPalette: ['#f6f5f0', '#e43615'],
    rarity: 'Rare',
    scaleType: 'Doitsu (Scaleless/Mirror)',
  },
  {
    id: 16,
    name: 'Goshiki (Juvenile)',
    kanji: '五色',
    romaji: 'Goshiki',
    variety: 'goshiki',
    category: 'Kawarimono',
    size: 'small',
    lengthCm: 27,
    description: 'The "Five-Colored" koi. A mysterious palette blending white, black, blue, red, and purple beneath an intricate shadow net.',
    patternDescription: 'Deep twilight shaded body with vivid red dorsal markings.',
    colorPalette: ['#596677', '#c93018', '#2a2b30', '#eae8e4'],
    rarity: 'Rare',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 17,
    name: 'Benigoi (Juvenile)',
    kanji: '紅鯉',
    romaji: 'Benigoi',
    variety: 'benigoi',
    category: 'Kawarimono',
    size: 'small',
    lengthCm: 23,
    description: 'A totally solid deep scarlet koi, even possessing red fins and a red belly. Brings good fortune to the garden according to tradition.',
    patternDescription: 'Uniform intense crimson-red across the entire body.',
    colorPalette: ['#d73e16', '#eb5c34'],
    rarity: 'Uncommon',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 18,
    name: 'Ochiba Shigure',
    kanji: '落葉時雨',
    romaji: 'Ochiba Shigure',
    variety: 'ochiba',
    category: 'Kawarimono',
    size: 'medium',
    lengthCm: 48,
    description: '"Autumn Leaves Fallen on Water". Soft slate-blue body resembling still autumn rain puddles, with bronze-brown patches like fallen maple leaves.',
    patternDescription: 'Blue-grey field with warm golden-brown patches reminiscent of fallen leaves.',
    colorPalette: ['#7d8c9a', '#9e6231', '#d4cfc7'],
    rarity: 'Rare',
    scaleType: 'Wagoi (Scaled)',
  },
  {
    id: 19,
    name: 'Kohaku (Gin Rin Juvenile)',
    kanji: '銀鱗若紅白',
    romaji: 'Gin Rin Waka Kohaku',
    variety: 'kohaku',
    category: 'Gosanke',
    size: 'small',
    lengthCm: 24,
    description: 'A lively young Kohaku whose scales catch the sun like glittering diamonds. Glides playfully through the water lily stems.',
    patternDescription: 'Compact two-step red pattern with diamond-sparkle scales.',
    colorPalette: ['#ffffff', '#e83e1b', '#f5f5f5'],
    rarity: 'Rare',
    scaleType: 'Gin Rin (Diamond Scaled)',
  },
];
